name: keepassxc
version: 2.4.1
grade: stable
summary: Community-driven port of the Windows application “KeePass Password Safe”
description: |
  KeePassXC is an application for people with extremely high demands on secure
  personal data management. It has a light interface, is cross-platform and
  published under the terms of the GNU General Public License.
confinement: strict
base: core18

plugs:
  icon-themes: # fix mouse cursor theme
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  keepassxc:
    command: desktop-launch keepassxc
    plugs: [unity7, x11, opengl, gsettings, home, network, network-bind, removable-media, raw-usb, wayland, desktop-legacy]
    desktop: usr/share/applications/org.keepassxc.KeePassXC.desktop
    environment:
      DISABLE_WAYLAND: 1
  cli:
    command: keepassxc-cli
    plugs: [gsettings, home, removable-media, raw-usb]
  proxy:
    command: keepassxc-proxy
    plugs: [home]

parts:
  keepassxc:
    source: .
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DKEEPASSXC_DIST_TYPE=Snap
      - -DKEEPASSXC_BUILD_TYPE=Release
      - -DWITH_TESTS=OFF
      - -DWITH_XC_ALL=ON
      - -DWITH_XC_KEESHARE_SECURE=ON
    build-packages:
      - g++
      - libgcrypt20-dev
      - libqt5x11extras5-dev
      - libqt5svg5-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g-dev
      - libxi-dev
      - libxtst-dev
      - libyubikey-dev
      - libykpers-1-dev
      - libsodium-dev
      - libargon2-0-dev
      - libqrencode-dev
      - libquazip5-dev
    stage-packages:
      - dbus
      - qttranslations5-l10n # common translations
      - libgcrypt20
      - libykpers-1-1
      - libargon2-0
      - libsodium23
      - libxtst6
      - libqt5x11extras5
      - libqt5svg5
      - libqrencode3
      - libqt5concurrent5
      - libquazip5-1
      - libusb-1.0-0
      - qtwayland5
      - qt5-style-plugins # for mouse cursor theme fix
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=keepassxc|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/keepassxc.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.keepassxc.KeePassXC.desktop
    organize:
      usr/share/qt5/translations/*.qm: usr/share/keepassxc/translations/
    stage:
      - -opt
    after: [desktop-qt5]
    
  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
